# Generated by Django 4.2.1 on 2023-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("race_ethnicity", models.CharField(max_length=50)),
                ("Parental_level_of_education", models.CharField(max_length=100)),
                ("lunch", models.CharField(max_length=50)),
                ("test_preparation", models.CharField(max_length=50)),
                ("math_score", models.IntegerField()),
                ("reading_score", models.IntegerField()),
                ("writing_score", models.IntegerField()),
                ("total_score", models.IntegerField()),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
