# Generated by Django 4.2.1 on 2023-09-20 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="student",
            name="total_score",
        ),
    ]
