# Generated by Django 4.2 on 2023-09-06 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HackernewsId",
            fields=[
                (
                    "hackernews",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fetched_at",
                    models.DateField(
                        default=datetime.datetime(2023, 9, 6, 12, 55, 17, 3272)
                    ),
                ),
            ],
        ),
    ]
